version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger-ov
services:
  ca0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: ca0.agiletech.vn
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    networks:
      hyperledger-ov:
        aliases:
        - ca_peerOrg1
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org1
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.agiletech.vn-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6fea2da26d7ec1cb94992ed10a2f579a0e646b6ccd46463076741db52f209e4b_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.agiletech.vn-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6fea2da26d7ec1cb94992ed10a2f579a0e646b6ccd46463076741db52f209e4b_sk -b admin:adminpw
      -d'
    volumes:
    - ./crypto-config/peerOrganizations/org1.agiletech.vn/ca/:/etc/hyperledger/fabric-ca-server-config
  ca1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: ca1.agiletech.vn
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    networks:
      hyperledger-ov:
        aliases:
        - ca_peerOrg2
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org2
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.agiletech.vn-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/dafeb23ab2c9f3441db36634b628316460dbd0ead7a959a1288cfdde4a733eca_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.agiletech.vn-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/dafeb23ab2c9f3441db36634b628316460dbd0ead7a959a1288cfdde4a733eca_sk -b admin:adminpw
      -d'
    volumes:
    - ./crypto-config/peerOrganizations/org2.agiletech.vn/ca/:/etc/hyperledger/fabric-ca-server-config
